import PDFDocument from 'pdfkit';
import ExcelJS from 'exceljs';
import fs from 'fs';
import path from 'path';

export const generatePDFReport = async (fraudResults, fileName = 'fraud_report.pdf') => {
  return new Promise((resolve, reject) => {
    try {
      const reportsDir = 'reports/';
      if (!fs.existsSync(reportsDir)) {
        fs.mkdirSync(reportsDir, { recursive: true });
      }
      
      const filePath = path.join(reportsDir, fileName);
      const doc = new PDFDocument({ margin: 50 });
      const stream = fs.createWriteStream(filePath);
      
      doc.pipe(stream);
      
      // Header
      doc.fontSize(24).font('Helvetica-Bold').text('AEGIS-AI Fraud Detection Report', {
        align: 'center'
      });
      doc.moveDown();
      
      // Summary Section
      doc.fontSize(16).font('Helvetica-Bold').text('Executive Summary', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(12).font('Helvetica');
      doc.text(`Report Generated: ${new Date().toLocaleString()}`);
      doc.text(`Total Invoices Analyzed: ${fraudResults.summary.total_invoices}`);
      doc.text(`Suspicious Invoices: ${fraudResults.summary.suspicious_count}`);
      doc.text(`Clean Invoices: ${fraudResults.summary.clean_count}`);
      doc.text(`Overall Risk Score: ${(fraudResults.summary.overall_risk_score * 100).toFixed(2)}%`);
      doc.moveDown();
      
      // Risk Distribution
      doc.fontSize(14).font('Helvetica-Bold').text('Risk Distribution');
      doc.fontSize(12).font('Helvetica');
      doc.text(`• High Risk: ${fraudResults.summary.high_risk_count} invoices`);
      doc.text(`• Medium Risk: ${fraudResults.summary.medium_risk_count} invoices`);
      doc.text(`• Low Risk: ${fraudResults.summary.low_risk_count} invoices`);
      doc.moveDown();
      
      // Detailed Analysis
      doc.fontSize(16).font('Helvetica-Bold').text('Detailed Analysis', { underline: true });
      doc.moveDown(0.5);
      
      fraudResults.predictions.forEach((pred, index) => {
        if (doc.y > 650) {
          doc.addPage();
        }
        
        doc.fontSize(12).font('Helvetica-Bold');
        doc.text(`Invoice ${index + 1}: ${pred.invoice_no}`, { continued: false });
        
        doc.fontSize(10).font('Helvetica');
        doc.text(`Vendor: ${pred.vendor}`);
        doc.text(`Fraud Probability: ${pred.fraud_probability.toFixed(2)}%`);
        doc.text(`Status: ${pred.is_suspicious ? 'SUSPICIOUS' : 'CLEAN'}`);
        doc.text(`Recommendation: ${pred.recommendation}`);
        
        doc.fontSize(10).font('Helvetica-Bold').text('Top Risk Factors:');
        doc.fontSize(9).font('Helvetica');
        pred.top_reasons.slice(0, 3).forEach(reason => {
          doc.text(`  • ${reason.description}`, { indent: 20 });
        });
        
        doc.moveDown();
      });
      
      // Footer
      doc.fontSize(8).text('Generated by AEGIS-AI - Universal AI-Powered Financial Safety Platform', {
        align: 'center',
        baseline: 'bottom'
      });
      
      doc.end();
      
      stream.on('finish', () => {
        console.log(`✅ PDF report generated: ${filePath}`);
        resolve(filePath);
      });
      
      stream.on('error', reject);
      
    } catch (error) {
      reject(error);
    }
  });
};

export const generateExcelReport = async (fraudResults, fileName = 'fraud_report.xlsx') => {
  try {
    const reportsDir = 'reports/';
    if (!fs.existsSync(reportsDir)) {
      fs.mkdirSync(reportsDir, { recursive: true });
    }
    
    const filePath = path.join(reportsDir, fileName);
    const workbook = new ExcelJS.Workbook();
    
    // Summary Sheet
    const summarySheet = workbook.addWorksheet('Summary');
    summarySheet.columns = [
      { header: 'Metric', key: 'metric', width: 30 },
      { header: 'Value', key: 'value', width: 20 }
    ];
    
    summarySheet.addRows([
      { metric: 'Report Generated', value: new Date().toLocaleString() },
      { metric: 'Total Invoices', value: fraudResults.summary.total_invoices },
      { metric: 'Suspicious Invoices', value: fraudResults.summary.suspicious_count },
      { metric: 'Clean Invoices', value: fraudResults.summary.clean_count },
      { metric: 'Overall Risk Score', value: `${(fraudResults.summary.overall_risk_score * 100).toFixed(2)}%` },
      { metric: 'High Risk Count', value: fraudResults.summary.high_risk_count },
      { metric: 'Medium Risk Count', value: fraudResults.summary.medium_risk_count },
      { metric: 'Low Risk Count', value: fraudResults.summary.low_risk_count }
    ]);
    
    // Style summary sheet
    summarySheet.getRow(1).font = { bold: true };
    summarySheet.getRow(1).fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF667EEA' }
    };
    
    // Detailed Analysis Sheet
    const detailSheet = workbook.addWorksheet('Detailed Analysis');
    detailSheet.columns = [
      { header: 'Invoice No', key: 'invoice_no', width: 15 },
      { header: 'Vendor', key: 'vendor', width: 30 },
      { header: 'Fraud Probability (%)', key: 'fraud_probability', width: 20 },
      { header: 'Status', key: 'status', width: 15 },
      { header: 'Risk Level', key: 'risk_level', width: 15 },
      { header: 'Recommendation', key: 'recommendation', width: 50 },
      { header: 'Top Risk Factor 1', key: 'reason1', width: 40 },
      { header: 'Top Risk Factor 2', key: 'reason2', width: 40 },
      { header: 'Top Risk Factor 3', key: 'reason3', width: 40 }
    ];
    
    fraudResults.predictions.forEach(pred => {
      const getRiskLevel = (score) => {
        if (score > 0.8) return 'HIGH';
        if (score > 0.6) return 'MEDIUM';
        if (score > 0.4) return 'LOW';
        return 'MINIMAL';
      };
      
      detailSheet.addRow({
        invoice_no: pred.invoice_no,
        vendor: pred.vendor,
        fraud_probability: pred.fraud_probability.toFixed(2),
        status: pred.is_suspicious ? 'SUSPICIOUS' : 'CLEAN',
        risk_level: getRiskLevel(pred.fraud_score),
        recommendation: pred.recommendation,
        reason1: pred.top_reasons[0]?.description || '',
        reason2: pred.top_reasons[1]?.description || '',
        reason3: pred.top_reasons[2]?.description || ''
      });
    });
    
    // Style detail sheet
    detailSheet.getRow(1).font = { bold: true };
    detailSheet.getRow(1).fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF667EEA' }
    };
    
    // Conditional formatting for fraud probability
    detailSheet.eachRow((row, rowNumber) => {
      if (rowNumber > 1) {
        const fraudProb = parseFloat(row.getCell('fraud_probability').value);
        if (fraudProb > 60) {
          row.getCell('status').fill = {
            type: 'pattern',
            pattern: 'solid',
            fgColor: { argb: 'FFEF4444' }
          };
        }
      }
    });
    
    await workbook.xlsx.writeFile(filePath);
    console.log(`✅ Excel report generated: ${filePath}`);
    
    return filePath;
  } catch (error) {
    throw new Error(`Excel report generation failed: ${error.message}`);
  }
};
